import "./globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial",
    template: "%s | Next.js Tutorial",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ padding: "1rem", backgroundColor: "#f0f0f0" }}>
          <h1>This header</h1>
        </header>
        {children}
        <footer style={{ padding: "1rem", backgroundColor: "#f0f0f0" }}>
          <h1>© 2024 Next.js Tutorial</h1>
        </footer>
      </body>
    </html>
  );
}
